version: '3.8'

services:
  swarm-manager:
    image: docker:dind
    privileged: true
    hostname: swarm-manager
    ports:
      - "2375:2375" # Docker daemon port for external access
      - "8000:8000" # dsctl-server API port (will be published by the service)
    environment:
      DOCKER_TLS_CERTDIR: "" # Disable TLS for simplicity in test environment
    networks:
      - test_net

networks:
  test_net:
    driver: bridge
