version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./dsctl_server:/home/appuser/dsctl_server
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
