"""Add display_name field to docker_hosts

Revision ID: 9c4d3dece253
Revises: 187dc20e6fd5
Create Date: 2025-07-06 19:34:54.357129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4d3dece253'
down_revision = '187dc20e6fd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docker_hosts', sa.Column('display_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docker_hosts', 'display_name')
    # ### end Alembic commands ###