name: Build Client and Server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Build Server Docker Image
      run: docker compose build

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and Push Server Docker Image to GHCR
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/dsctl-server
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\([^-]*\).*$,\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/v*" ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker buildx to get the image ID
        BUILDX_OUTPUT=$(docker buildx build --tag $IMAGE_ID:$VERSION --output type=image,name=$IMAGE_ID,push=true .)
        echo "$BUILDX_OUTPUT"

    - name: Verify Client Setup
      run: poetry run python dsctl_cli/main.py --help
